FROM golang:1.25-alpine

WORKDIR /app

COPY user_service/go.mod user_service/go.sum ./
RUN go mod download

COPY user_service/cmd ./cmd

RUN go build -o server ./cmd/main.go

EXPOSE 8080
CMD ["./server"]